include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - always_declare_return_types
    - avoid_multiple_declarations_per_line
    - prefer_relative_imports
    - prefer_single_quotes
