name: precificapp
description: "Erika Precifica"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cookie_jar: ^4.0.8
  device_info_plus: ^11.0.0
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  email_validator: ^3.0.0
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_in_app_messaging: ^0.8.0+8
  firebase_messaging: ^15.1.3
  firebase_performance: ^0.10.0+8
  firebase_remote_config: ^5.1.3
  flutter:
    sdk: flutter
  flutter_flavorizr: ^2.2.3
  flutter_native_splash: ^2.4.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  go_router: ^14.2.9
  local_auth: ^2.3.0
  package_info_plus: ^8.0.3
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  rx_notifier: ^2.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/launcher_icon.png"
  remove_alpha_ios: true
  background_color_ios: "#F12838"

flavorizr:
  flavors:
    dev:
      app:
        name: "Erika Precifica - Dev"

      android:
        applicationId: "br.com.erikaprecifica.precifikapp.dev"
        firebase:
          config: ".firebase/dev/google-services.json"
      ios:
        bundleId: "br.com.erikaprecifica.precifikapp.dev"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"

    prod:
      app:
        name: "Erika Precifica"

      android:
        applicationId: "br.com.erikaprecifica.precifikapp"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "br.com.erikaprecifica.precifikapp"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"

flutter_native_splash:
  color: "#F12838"
  color_dark: "#F12838"
  image: assets/splash/splash.png
  image_dark: assets/splash/splash.png

  android_12:
    color: "#F12838"
    color_dark: "#F12838"
    image: assets/splash/splash.png
    image_dark: assets/splash/splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/light/bold/
    - assets/icons/light/linear/
    - assets/icons/light/outline/
    - assets/icons/light/solid/
    - assets/icons/light/twotone/
    - assets/images/
    - assets/jsons/
    - assets/splash/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets\fonts\jakarta\PlusJakartaSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets\fonts\jakarta\PlusJakartaSans-Medium.ttf
          style: normal
          weight: 500
        - asset: assets\fonts\jakarta\PlusJakartaSans-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets\fonts\jakarta\PlusJakartaSans-Bold.ttf
          style: normal
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets\fonts\worksans\WorkSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets\fonts\worksans\WorkSans-Medium.ttf
          style: normal
          weight: 500
        - asset: assets\fonts\worksans\WorkSans-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets\fonts\worksans\WorkSans-Bold.ttf
          style: normal
          weight: 700
