name: precificapp
description: "Erika Precifica"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_in_app_messaging: ^0.8.0+8
  firebase_messaging: ^15.1.3
  firebase_performance: ^0.10.0+8
  firebase_remote_config: ^5.1.3
  flutter:
    sdk: flutter
  flutter_flavorizr: ^2.2.3
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flavorizr:
  flavors:
    dev:
      app:
        name: "Erika Precifica - Dev"

      android:
        applicationId: "br.com.erikaprecifica.precifikapp.dev"
        firebase:
          config: ".firebase/dev/google-services.json"
      ios:
        bundleId: "br.com.erikaprecifica.precifikapp.dev"
        firebase:
          config: ".firebase/dev/GoogleService-Info.plist"

    prod:
      app:
        name: "Erika Precifica"

      android:
        applicationId: "br.com.erikaprecifica.precifikapp"
        firebase:
          config: ".firebase/prod/google-services.json"
      ios:
        bundleId: "br.com.erikaprecifica.precifikapp"
        firebase:
          config: ".firebase/prod/GoogleService-Info.plist"

flutter_native_splash:
  color: "#F12838"
  image: assets/splash/splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/light/bold/
    - assets/icons/light/linear/
    - assets/icons/light/outline/
    - assets/icons/light/solid/
    - assets/icons/light/twotone/
    - assets/images/
    - assets/jsons/
    - assets/splash/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets\fonts\jakarta\PlusJakartaSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets\fonts\jakarta\PlusJakartaSans-Medium.ttf
          style: normal
          weight: 500
        - asset: assets\fonts\jakarta\PlusJakartaSans-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets\fonts\jakarta\PlusJakartaSans-Bold.ttf
          style: normal
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets\fonts\worksans\WorkSans-Regular.ttf
          style: normal
          weight: 400
        - asset: assets\fonts\worksans\WorkSans-Medium.ttf
          style: normal
          weight: 500
        - asset: assets\fonts\worksans\WorkSans-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets\fonts\worksans\WorkSans-Bold.ttf
          style: normal
          weight: 700
    - family: MyProfitIcons
      fonts:
        - asset: assets\fonts\CustomMyProfitIcons\custommyprofiticons.ttf
          style: normal
          weight: 400
